/**
 * Official Class Legger Data & Standard Roster Definitions
 * SMK NU UNGARAN - TAHUN PELAJARAN 2026/2027
 * Document Source: Dokumen Legger Nilai & Daftar Siswa Per Kelas
 */

export interface LeggerStudentItem {
  no: number
  nis: string
  name: string
  gender: 'L' | 'P'
}

export interface ClassLeggerDefinition {
  classKey: string // e.g. "X-TJKT-1" or "XI-TJKT-1" or "XII-TJKT-1"
  className: string
  level: 'X' | 'XI' | 'XII'
  majorCode: 'TJKT' | 'BP' | 'DKV' | 'TE' | 'TO'
  majorName: string
  rombel: number
  homeroomTeacherName: string
  maleCount: number
  femaleCount: number
  totalCount: number
  students: LeggerStudentItem[]
}

// Complete verified dataset for Grade X from pages 1-16
export const VERIFIED_GRADE_X_LEGGERS: ClassLeggerDefinition[] = [
  // 1. X-TJKT-1 (Page 1)
  {
    classKey: 'X-TJKT-1',
    className: 'X-TJKT-1',
    level: 'X',
    majorCode: 'TJKT',
    majorName: 'Teknik Jaringan Komputer dan Telekomunikasi',
    rombel: 1,
    homeroomTeacherName: 'Ratna Purnamasari, S.Pd.',
    maleCount: 26,
    femaleCount: 10,
    totalCount: 36,
    students: [
      { no: 1, nis: 'TJKT.26-3114', name: 'Adi Priatmoko', gender: 'L' },
      { no: 2, nis: 'TJKT.26-3115', name: 'Ahmad Adi Nur', gender: 'L' },
      { no: 3, nis: 'TJKT.26-3116', name: 'Ahmad Arafiq', gender: 'L' },
      { no: 4, nis: 'TJKT.26-3117', name: 'Aisha Nur Medina', gender: 'P' },
      { no: 5, nis: 'TJKT.26-3118', name: 'Amelia Cahya Putri', gender: 'P' },
      { no: 6, nis: 'TJKT.26-3119', name: 'Arya Meindra Nugraha', gender: 'L' },
      { no: 7, nis: 'TJKT.26-3120', name: 'Carissa Putri', gender: 'P' },
      { no: 8, nis: 'TJKT.26-3121', name: 'Eka Maya Immatul Fitriyani', gender: 'P' },
      { no: 9, nis: 'TJKT.26-3122', name: 'Errissa Attama Resti', gender: 'P' },
      { no: 10, nis: 'TJKT.26-3123', name: 'Fahira Isnaini Ramadhani', gender: 'P' },
      { no: 11, nis: 'TJKT.26-3124', name: 'Ghani Ahmada Zulfakhi', gender: 'L' },
      { no: 12, nis: 'TJKT.26-3125', name: 'Kaka Rizki Anditya', gender: 'L' },
      { no: 13, nis: 'TJKT.26-3126', name: 'Kurnia Cahya Muhamad', gender: 'L' },
      { no: 14, nis: 'TJKT.26-3127', name: 'Melina Riyani', gender: 'P' },
      { no: 15, nis: 'TJKT.26-3128', name: 'Mohammat Rafi Aprillio', gender: 'L' },
      { no: 16, nis: 'TJKT.26-3129', name: 'Muhamad Ibnu Latif', gender: 'L' },
      { no: 17, nis: 'TJKT.26-3131', name: 'Muhammad Najib Bintang Jannata', gender: 'L' },
      { no: 18, nis: 'TJKT.26-3130', name: 'Muhammad Ridho Hidayat', gender: 'L' },
      { no: 19, nis: 'TJKT.26-3132', name: 'Muhammad Zaka Al Zidan', gender: 'L' },
      { no: 20, nis: 'TJKT.26-3133', name: 'Muhammad Zaqfa Suhendar', gender: 'L' },
      { no: 21, nis: 'TJKT.26-3134', name: 'Mukhammad Zidan Shofa', gender: 'L' },
      { no: 22, nis: 'TJKT.26-3135', name: 'Murinho Putra Pratama', gender: 'L' },
      { no: 23, nis: 'TJKT.26-3136', name: 'Nailly Putri Halistyaningrum', gender: 'P' },
      { no: 24, nis: 'TJKT.26-3137', name: 'Raditya Dante Bramacari', gender: 'L' },
      { no: 25, nis: 'TJKT.26-3138', name: 'Rafa Dwi Kurniawan', gender: 'L' },
      { no: 26, nis: 'TJKT.26-3139', name: 'Rafqy Irzan Dafinza', gender: 'L' },
      { no: 27, nis: 'TJKT.26-3140', name: 'Raiyan Abdul Rokhim', gender: 'L' },
      { no: 28, nis: 'TJKT.26-3141', name: 'Rasya Patoh', gender: 'L' },
      { no: 29, nis: 'TJKT.26-3142', name: 'Rengga Ari Setyo', gender: 'L' },
      { no: 30, nis: 'TJKT.26-3143', name: 'Rifki Velenniko Variyansah', gender: 'L' },
      { no: 31, nis: 'TJKT.26-3144', name: 'Rio Ferdinan', gender: 'L' },
      { no: 32, nis: 'TJKT.26-3145', name: 'Tegar Damar Eka Saputra', gender: 'L' },
      { no: 33, nis: 'TJKT.26-3146', name: 'Tiara Hepriliana', gender: 'P' },
      { no: 34, nis: 'TJKT.26-3147', name: 'Valya Putri Faeruza', gender: 'P' },
      { no: 35, nis: 'TJKT.26-3148', name: "Ya'kub", gender: 'L' },
      { no: 36, nis: 'TJKT.26-3149', name: 'Zaqki Maulana Hidayat', gender: 'L' }
    ]
  },
  // 2. X-TJKT-2 (Page 2)
  {
    classKey: 'X-TJKT-2',
    className: 'X-TJKT-2',
    level: 'X',
    majorCode: 'TJKT',
    majorName: 'Teknik Jaringan Komputer dan Telekomunikasi',
    rombel: 2,
    homeroomTeacherName: 'Agus Pujianto, S.Pd., M.Pd.',
    maleCount: 26,
    femaleCount: 10,
    totalCount: 36,
    students: [
      { no: 1, nis: 'TJKT.26-3150', name: 'Agung Ahmad Pamungkas', gender: 'L' },
      { no: 2, nis: 'TJKT.26-3151', name: 'Ahmad Nizam Nufail Shihab', gender: 'L' },
      { no: 3, nis: 'TJKT.26-3152', name: 'Aldy Dian Saputra', gender: 'L' },
      { no: 4, nis: 'TJKT.26-3153', name: 'Althaf Sakhi Firjatullah', gender: 'L' },
      { no: 5, nis: 'TJKT.26-3154', name: 'Alvin Chaesarrano Hermawan', gender: 'L' },
      { no: 6, nis: 'TJKT.26-3155', name: 'Alvin Julian Kristanto', gender: 'L' },
      { no: 7, nis: 'TJKT.26-3156', name: 'Aqila Muhammad Fahmi', gender: 'L' },
      { no: 8, nis: 'TJKT.26-3157', name: 'Auliya Hasan', gender: 'P' },
      { no: 9, nis: 'TJKT.26-3158', name: 'Bagus Mahendra', gender: 'L' },
      { no: 10, nis: 'TJKT.26-3159', name: 'Binti Jauharotul Maknum', gender: 'P' },
      { no: 11, nis: 'TJKT.26-3160', name: 'Candra Haris Maulana', gender: 'L' },
      { no: 12, nis: 'TJKT.26-3161', name: 'Diah Ayu Lestari', gender: 'P' },
      { no: 13, nis: 'TJKT.26-3162', name: 'Dyas Adam Saputra', gender: 'L' },
      { no: 14, nis: 'TJKT.26-3163', name: 'Erryn Hany Asyifa Latief', gender: 'P' },
      { no: 15, nis: 'TJKT.26-3164', name: 'Fanda Dwi Kurniawan', gender: 'L' },
      { no: 16, nis: 'TJKT.26-3165', name: 'Farindra Dea Ayu Anggraeni', gender: 'P' },
      { no: 17, nis: 'TJKT.26-3166', name: 'Fatimah Amira', gender: 'P' },
      { no: 18, nis: 'TJKT.26-3167', name: 'Giovani Faizal Tsaqif', gender: 'L' },
      { no: 19, nis: 'TJKT.26-3168', name: 'Ilham Nur Fadzilah', gender: 'L' },
      { no: 20, nis: 'TJKT.26-3169', name: 'Khusnu Herka Ardyansyah', gender: 'L' },
      { no: 21, nis: 'TJKT.26-3170', name: 'Mahardika Kusumawardhani', gender: 'P' },
      { no: 22, nis: 'TJKT.26-3171', name: 'Maulana Faadhil Saabiq Arifa', gender: 'L' },
      { no: 23, nis: 'TJKT.26-3172', name: 'Miftah Risqi Barokah', gender: 'L' },
      { no: 24, nis: 'TJKT.26-3173', name: 'Muhamad Nazilul Khanafi', gender: 'L' },
      { no: 25, nis: 'TJKT.26-3174', name: 'Muhamad Revan Dias Candra', gender: 'L' },
      { no: 26, nis: 'TJKT.26-3175', name: 'Muhammad Khafifudin', gender: 'L' },
      { no: 27, nis: 'TJKT.26-3176', name: 'Muhammad Rizki Maulana', gender: 'L' },
      { no: 28, nis: 'TJKT.26-3177', name: 'Muhammad Zakky Mubarok', gender: 'L' },
      { no: 29, nis: 'TJKT.26-3178', name: 'Naysilla Kurnia Rachmadani', gender: 'P' },
      { no: 30, nis: 'TJKT.26-3179', name: 'Rakha Aditya Wicaksana', gender: 'L' },
      { no: 31, nis: 'TJKT.26-3180', name: 'Raoz Zaed Prayogo', gender: 'L' },
      { no: 32, nis: 'TJKT.26-3181', name: 'Ridho Ardan Maulana', gender: 'L' },
      { no: 33, nis: 'TJKT.26-3182', name: 'Rifki Ardianto', gender: 'L' },
      { no: 34, nis: 'TJKT.26-3183', name: 'Safa Dwi Nugroho', gender: 'L' },
      { no: 35, nis: 'TJKT.26-3184', name: 'Syafa Lutfiana Faizah', gender: 'P' },
      { no: 36, nis: 'TJKT.26-3185', name: 'Talita Aini Salsabila', gender: 'P' }
    ]
  },
  // 3. X-TJKT-3 (Page 3)
  {
    classKey: 'X-TJKT-3',
    className: 'X-TJKT-3',
    level: 'X',
    majorCode: 'TJKT',
    majorName: 'Teknik Jaringan Komputer dan Telekomunikasi',
    rombel: 3,
    homeroomTeacherName: 'Siti Nur Asiyah, S.Pd.I.',
    maleCount: 28,
    femaleCount: 7,
    totalCount: 35,
    students: [
      { no: 1, nis: 'TJKT.26-3186', name: 'Achmad Eka Khanafi', gender: 'L' },
      { no: 2, nis: 'TJKT.26-3188', name: 'Ahmad Fahad Nur Kautsar', gender: 'L' },
      { no: 3, nis: 'TJKT.26-3187', name: 'Ahmad Gofar Maulana Ibrahim Moufiq', gender: 'L' },
      { no: 4, nis: 'TJKT.26-3189', name: 'Aisha Firdausy', gender: 'P' },
      { no: 5, nis: 'TJKT.26-3190', name: 'Alif Tirta Saputra', gender: 'L' },
      { no: 6, nis: 'TJKT.26-3191', name: "Amar Ma'ruf Ardhiansyah", gender: 'L' },
      { no: 7, nis: 'TJKT.26-3192', name: 'Ayu Pradani Aruningtyas', gender: 'P' },
      { no: 8, nis: 'TJKT.26-3193', name: 'Bintang Tristian Ramadhan', gender: 'L' },
      { no: 9, nis: 'TJKT.26-3194', name: 'Daris Nur Fikri', gender: 'L' },
      { no: 10, nis: 'TJKT.26-3195', name: 'Davin Nadil Annafis', gender: 'L' },
      { no: 11, nis: 'TJKT.26-3196', name: 'Dhimitri Rastayova Putra Sadewa', gender: 'L' },
      { no: 12, nis: 'TJKT.26-3197', name: 'Dinda Puspita Sari', gender: 'P' },
      { no: 13, nis: 'TJKT.26-3198', name: 'Excel Putra Pratama', gender: 'L' },
      { no: 14, nis: 'TJKT.26-3199', name: 'Faiq Arba Muhamad', gender: 'L' },
      { no: 15, nis: 'TJKT.26-3200', name: 'Farelio Hanggayuda Meiky', gender: 'L' },
      { no: 16, nis: 'TJKT.26-3201', name: 'Fidiyah Nurwiduri', gender: 'P' },
      { no: 17, nis: 'TJKT.26-3204', name: 'Ifan Maulana Ilham', gender: 'L' },
      { no: 18, nis: 'TJKT.26-3205', name: 'Ira Safitri', gender: 'P' },
      { no: 19, nis: 'TJKT.26-3206', name: 'Izy Tahta Ega Saputra', gender: 'L' },
      { no: 20, nis: 'TJKT.26-3207', name: 'Kafa Lutfi Abqori', gender: 'L' },
      { no: 21, nis: 'TJKT.26-3208', name: 'Lucky Bagas Eko Saputro', gender: 'L' },
      { no: 22, nis: 'TJKT.26-3259', name: 'Lutfil Khakim', gender: 'L' },
      { no: 23, nis: 'TJKT.26-3209', name: "Meyla Nur Putri'A", gender: 'P' },
      { no: 24, nis: 'TJKT.26-3210', name: 'Mohamad Afandi', gender: 'L' },
      { no: 25, nis: 'TJKT.26-3260', name: 'Mohamad Airlangga Yuda Pratama', gender: 'L' },
      { no: 26, nis: 'TJKT.26-3212', name: 'Muhamad Samsul Khoerudin', gender: 'L' },
      { no: 27, nis: 'TJKT.26-3213', name: 'Muhammad Andikayana Saputra', gender: 'L' },
      { no: 28, nis: 'TJKT.26-3214', name: 'Muhammad Ardhan Firdaus', gender: 'L' },
      { no: 29, nis: 'TJKT.26-3215', name: 'Muhammad Ardiansyah', gender: 'L' },
      { no: 30, nis: 'TJKT.26-3216', name: 'Muhammad Ibnu Abdillah', gender: 'L' },
      { no: 31, nis: 'TJKT.26-3211', name: 'Muhammad Reyhan Rinaldi', gender: 'L' },
      { no: 32, nis: 'TJKT.26-3217', name: 'Nanda Ayu Diya Ningratri', gender: 'P' },
      { no: 33, nis: 'TJKT.26-3218', name: 'Naufal Ramadhan', gender: 'L' },
      { no: 34, nis: 'TJKT.26-3220', name: 'Rangga Saputra', gender: 'L' },
      { no: 35, nis: 'TJKT.26-3221', name: 'Wisnu Satrio Wijoyo Kusumo', gender: 'L' }
    ]
  },
  // 4. X-TJKT-4 (Page 4)
  {
    classKey: 'X-TJKT-4',
    className: 'X-TJKT-4',
    level: 'X',
    majorCode: 'TJKT',
    majorName: 'Teknik Jaringan Komputer dan Telekomunikasi',
    rombel: 4,
    homeroomTeacherName: 'Wahyu Ratnawati, S.Pd.',
    maleCount: 26,
    femaleCount: 10,
    totalCount: 36,
    students: [
      { no: 1, nis: 'TJKT.26-3222', name: 'Abu Siregar Al-Faberzta', gender: 'L' },
      { no: 2, nis: 'TJKT.26-3223', name: "Aflah In'am Nur Falah", gender: 'L' },
      { no: 3, nis: 'TJKT.26-3224', name: 'Al Anwari Joe Kienas', gender: 'L' },
      { no: 4, nis: 'TJKT.26-3225', name: 'Al Azzam Fiki Saputra', gender: 'L' },
      { no: 5, nis: 'TJKT.26-3226', name: "Alfiyan Fadlan Zaenni'am", gender: 'L' },
      { no: 6, nis: 'TJKT.26-3227', name: 'Alika Davin Widyadhana', gender: 'L' },
      { no: 7, nis: 'TJKT.26-3228', name: 'Ariawan Setya Ramdani', gender: 'L' },
      { no: 8, nis: 'TJKT.26-3229', name: 'Avinza Fachri Nugroho', gender: 'L' },
      { no: 9, nis: 'TJKT.26-3230', name: 'Beby Yulia Tatania Utama', gender: 'P' },
      { no: 10, nis: 'TJKT.26-3231', name: 'Brian Ahza Mahogra', gender: 'L' },
      { no: 11, nis: 'TJKT.26-3232', name: 'Fatar Nur Rohim', gender: 'L' },
      { no: 12, nis: 'TJKT.26-3233', name: 'Fernanda Abdil Al-Anshari', gender: 'L' },
      { no: 13, nis: 'TJKT.25-2977', name: 'Hanifa Khairunissa', gender: 'P' },
      { no: 14, nis: 'TJKT.26-3235', name: 'Irfan Nur Mahmud', gender: 'L' },
      { no: 15, nis: 'TJKT.26-3236', name: 'Irma Laela Firdaus', gender: 'P' },
      { no: 16, nis: 'TJKT.26-3237', name: 'Kelfin Zalfa Saputra', gender: 'L' },
      { no: 17, nis: 'TJKT.26-3238', name: 'Khoko Saputro', gender: 'L' },
      { no: 18, nis: 'TJKT.26-3239', name: 'Mikailla Alqueensa', gender: 'P' },
      { no: 19, nis: 'TJKT.26-3240', name: 'Muhamad Deva Dwi Cahya Pratama', gender: 'L' },
      { no: 20, nis: 'TJKT.26-3241', name: 'Muhamad Ridho Arrosid', gender: 'L' },
      { no: 21, nis: 'TJKT.26-3242', name: 'Muhammad Hafiz Ulil Albab', gender: 'L' },
      { no: 22, nis: 'TJKT.26-3243', name: 'Muhammad Nizam Khaqiqi', gender: 'L' },
      { no: 23, nis: 'TJKT.26-3244', name: 'Muhammad Zulfan Arya', gender: 'L' },
      { no: 24, nis: 'TJKT.26-3245', name: 'Nayaka Firaas Al Fayaadh', gender: 'L' },
      { no: 25, nis: 'TJKT.26-3246', name: 'Oktafiya Tifatul Mughiroh', gender: 'P' },
      { no: 26, nis: 'TJKT.26-3247', name: 'Puja Baskara', gender: 'L' },
      { no: 27, nis: 'TJKT.26-3248', name: 'Putri Aisyah', gender: 'P' },
      { no: 28, nis: 'TJKT.26-3249', name: 'Qatrunada Kirana Sahputri', gender: 'P' },
      { no: 29, nis: 'TJKT.26-3250', name: 'Raditya Ahmad Arjuna', gender: 'L' },
      { no: 30, nis: 'TJKT.26-3251', name: 'Reivan Alfa Rizqy', gender: 'L' },
      { no: 31, nis: 'TJKT.26-3252', name: 'Reza Atmadja Arga Prasetya', gender: 'L' },
      { no: 32, nis: 'TJKT.26-3253', name: 'Safa Nur Anzani', gender: 'P' },
      { no: 33, nis: 'TJKT.26-3254', name: 'Salsa Bella Putri Aryana', gender: 'P' },
      { no: 34, nis: 'TJKT.26-3255', name: 'Savannah Nadjah Rachbani', gender: 'P' },
      { no: 35, nis: 'TJKT.26-3256', name: 'Taufiq Malik Ibrahim', gender: 'L' },
      { no: 36, nis: 'TJKT.26-3257', name: 'Yudanta Kaffa Atmajaya', gender: 'L' }
    ]
  },
  // 5. X-BP-1 (Page 5)
  {
    classKey: 'X-BP-1',
    className: 'X-BP-1',
    level: 'X',
    majorCode: 'BP',
    majorName: 'Broadcasting dan Perfilman',
    rombel: 1,
    homeroomTeacherName: 'Dewi Anggi Anggraeni Ratnasari, S.Ds.',
    maleCount: 11,
    femaleCount: 25,
    totalCount: 36,
    students: [
      { no: 1, nis: 'BP.26-2063', name: 'Achmad Hanaffy', gender: 'L' },
      { no: 2, nis: 'BP.26-2064', name: 'Adinda Zahwa Widyani', gender: 'P' },
      { no: 3, nis: 'BP.26-2065', name: 'Adrian Fathin Maulana Hisam', gender: 'L' },
      { no: 4, nis: 'BP.26-2066', name: 'Agustina Dwi Wulan Suci', gender: 'P' },
      { no: 5, nis: 'BP.26-2067', name: 'Aizha Syifa Mahdiyyah', gender: 'P' },
      { no: 6, nis: 'BP.26-2068', name: 'Alfredo Insyafi Rheyda', gender: 'L' },
      { no: 7, nis: 'BP.26-2069', name: 'Angel Zuanita Wida Sari', gender: 'P' },
      { no: 8, nis: 'BP.26-2070', name: 'Aquilla Azka Salwa Azzahra', gender: 'P' },
      { no: 9, nis: 'BP.26-2071', name: 'Asyifa Nidaul Khusna', gender: 'P' },
      { no: 10, nis: 'BP.26-2072', name: 'Aulia Oktaviana', gender: 'P' },
      { no: 11, nis: 'BP.26-2073', name: 'Aulia Sifa Hairunisa', gender: 'P' },
      { no: 12, nis: 'BP.26-2074', name: 'Aurora Oktiseta Cahyaningtyas Wicaksono', gender: 'P' },
      { no: 13, nis: 'BP.26-2075', name: 'Calista Aqilah Rinaldo', gender: 'P' },
      { no: 14, nis: 'BP.26-2076', name: 'Charisa Agustina Saputri', gender: 'P' },
      { no: 15, nis: 'BP.26-2077', name: 'Dewi Puspita Ningsih', gender: 'P' },
      { no: 16, nis: 'BP.26-2078', name: 'Eki Ines Tata Alinski', gender: 'P' },
      { no: 17, nis: 'BP.26-2171', name: 'Faizal Ryan Hamdani', gender: 'L' },
      { no: 18, nis: 'BP.26-2079', name: 'Fajar Oktaviano', gender: 'L' },
      { no: 19, nis: 'BP.26-2080', name: 'Fatma Fazidatun Nikmah', gender: 'P' },
      { no: 20, nis: 'BP.26-2081', name: 'Karin Azzatul Maghfiroh', gender: 'P' },
      { no: 21, nis: 'BP.26-2082', name: 'Lafifa Athaya Nur Habibah', gender: 'P' },
      { no: 22, nis: 'BP.26-2083', name: 'Marsyella Maulida Karisa Putri', gender: 'P' },
      { no: 23, nis: 'BP.26-2084', name: "Maulida Nisa'ul Khusna", gender: 'P' },
      { no: 24, nis: 'BP.26-2085', name: 'Mayla Khanifah', gender: 'P' },
      { no: 25, nis: 'BP.26-2086', name: 'Michellin Dehlova', gender: 'P' },
      { no: 26, nis: 'BP.26-2087', name: 'Milla Radhia Malihah', gender: 'P' },
      { no: 27, nis: 'BP.26-2089', name: 'Nindya Kurniawati', gender: 'P' },
      { no: 28, nis: 'BP.26-2090', name: 'Rafael Permana Putra', gender: 'L' },
      { no: 29, nis: 'BP.26-2091', name: 'Raffa Maulana Akhsan', gender: 'L' },
      { no: 30, nis: 'BP.26-2092', name: 'Reno Aditya Pratama', gender: 'L' },
      { no: 31, nis: 'BP.26-2093', name: 'Rifa Maulana Azis', gender: 'P' },
      { no: 32, nis: 'BP.26-2094', name: 'Rizky Arridho', gender: 'L' },
      { no: 33, nis: 'BP.26-2095', name: 'Septi Firlina', gender: 'P' },
      { no: 34, nis: 'BP.26-2096', name: 'Sifa Aennur Ramadani', gender: 'P' },
      { no: 35, nis: 'BP.26-2097', name: 'Syarif Hidayatullah', gender: 'L' },
      { no: 36, nis: 'BP.26-2098', name: 'Yuwaji Atmojo', gender: 'L' }
    ]
  },
  // 6. X-BP-2 (Page 6)
  {
    classKey: 'X-BP-2',
    className: 'X-BP-2',
    level: 'X',
    majorCode: 'BP',
    majorName: 'Broadcasting dan Perfilman',
    rombel: 2,
    homeroomTeacherName: 'Ira Nur Baity Chasanah, S.Kom.',
    maleCount: 12,
    femaleCount: 24,
    totalCount: 36,
    students: [
      { no: 1, nis: 'BP.26-2099', name: 'Akmel Berliana', gender: 'P' },
      { no: 2, nis: 'BP.26-2100', name: 'Alisya Bilqis Syahla', gender: 'P' },
      { no: 3, nis: 'BP.26-2101', name: 'Alya Safira Ramadhani', gender: 'P' },
      { no: 4, nis: 'BP.26-2102', name: 'Arjuna Putra Pratama', gender: 'L' },
      { no: 5, nis: 'BP.26-2103', name: 'Asyifa Safa Mauliddah', gender: 'P' },
      { no: 6, nis: 'BP.26-2104', name: 'Atika Dhiaul Atha', gender: 'P' },
      { no: 7, nis: 'BP.26-2105', name: 'Aurelia Ekanuary Putri Framita', gender: 'P' },
      { no: 8, nis: 'BP.26-2106', name: 'Axcel Al Gofar', gender: 'L' },
      { no: 9, nis: 'BP.26-2107', name: 'Azwa Fauziya Qurnaini', gender: 'P' },
      { no: 10, nis: 'BP.26-2108', name: 'Bagas Ramadhan Susanto', gender: 'L' },
      { no: 11, nis: 'BP.26-2109', name: 'Dewi Wulan Purnamasari', gender: 'P' },
      { no: 12, nis: 'BP.26-2110', name: 'Eka Fajar Arzikna', gender: 'L' },
      { no: 13, nis: 'BP.26-2111', name: 'Fadhilatul Mukhoyaroh', gender: 'P' },
      { no: 14, nis: 'BP.26-2112', name: 'Giovani Zildan Hidayat', gender: 'L' },
      { no: 15, nis: 'BP.26-2113', name: 'Haikal Emran Latieef', gender: 'L' },
      { no: 16, nis: 'BP.26-2114', name: 'Intan Cahya Dewanti', gender: 'P' },
      { no: 17, nis: 'BP.26-2115', name: 'Kurnia Arva Jian Danica', gender: 'P' },
      { no: 18, nis: 'BP.26-2116', name: 'Muhammad Dhivano Arifin Ilham', gender: 'L' },
      { no: 19, nis: 'BP.26-2117', name: "Muhammad Hafidl 'Ulumuddin", gender: 'L' },
      { no: 20, nis: 'BP.26-2118', name: 'Muhammad Rafa Attalah Saputra', gender: 'L' },
      { no: 21, nis: 'BP.26-2119', name: 'Mutiara Salsabila', gender: 'P' },
      { no: 22, nis: 'BP.26-2120', name: 'Nathisya Nichen Ardiyanti', gender: 'P' },
      { no: 23, nis: 'BP.26-2121', name: 'Naya Noviyana', gender: 'P' },
      { no: 24, nis: 'BP.26-2122', name: 'Nirmala Dwi Karomah', gender: 'P' },
      { no: 25, nis: 'BP.26-2123', name: 'Noova Putri Ardiyanti', gender: 'P' },
      { no: 26, nis: 'BP.26-2124', name: 'Qayla Dinda Silviana', gender: 'P' },
      { no: 27, nis: 'BP.26-2125', name: 'Ricky Zhura Aditya', gender: 'L' },
      { no: 28, nis: 'BP.26-2126', name: 'Safira Ahya Sahila', gender: 'P' },
      { no: 29, nis: 'BP.26-2127', name: 'Sari Kumala Dewi', gender: 'P' },
      { no: 30, nis: 'BP.26-2128', name: 'Silfi A`Riful Aufa', gender: 'P' },
      { no: 31, nis: 'BP.26-2129', name: 'Silvi Limmilatimal Husna', gender: 'P' },
      { no: 32, nis: 'BP.26-2130', name: 'Vanessa Amelia Anfuri', gender: 'P' },
      { no: 33, nis: 'BP.26-2131', name: 'Via Namariqu Masfufah', gender: 'P' },
      { no: 34, nis: 'BP.26-2132', name: 'Yuda Atmaja', gender: 'L' },
      { no: 35, nis: 'BP.26-2133', name: 'Zada Arkananta', gender: 'L' },
      { no: 36, nis: 'BP.26-2134', name: 'Zaskia Mahira Putri', gender: 'P' }
    ]
  },
  // 7. X-BP-3 (Page 7)
  {
    classKey: 'X-BP-3',
    className: 'X-BP-3',
    level: 'X',
    majorCode: 'BP',
    majorName: 'Broadcasting dan Perfilman',
    rombel: 3,
    homeroomTeacherName: 'Riko Kurniawan, S.Pd.',
    maleCount: 10,
    femaleCount: 26,
    totalCount: 36,
    students: [
      { no: 1, nis: 'BP.26-2135', name: 'Ahmad Indra Setyawan', gender: 'L' },
      { no: 2, nis: 'BP.26-2136', name: 'Alviani Julia Saputri', gender: 'P' },
      { no: 3, nis: 'BP.26-2137', name: 'Anindya Maritza Niya Setiawan', gender: 'P' },
      { no: 4, nis: 'BP.26-2138', name: 'Azahra Naja Zharifah', gender: 'P' },
      { no: 5, nis: 'BP.26-2139', name: 'Azriel Manggala Mahardika', gender: 'L' },
      { no: 6, nis: 'BP.26-2140', name: 'Billie Aditia Dwi Chaya', gender: 'L' },
      { no: 7, nis: 'BP.26-2141', name: 'Bunga Citra Lestari', gender: 'P' },
      { no: 8, nis: 'BP.26-2142', name: 'Carissa Alilla Prawesti', gender: 'P' },
      { no: 9, nis: 'BP.26-2143', name: 'Citra Nanda Septiana', gender: 'P' },
      { no: 10, nis: 'BP.26-2144', name: 'Devi Wulan Anggraini', gender: 'P' },
      { no: 11, nis: 'BP.26-2145', name: 'Farda Arifa Salma', gender: 'P' },
      { no: 12, nis: 'BP.26-2146', name: 'Hanica Cika Kasila', gender: 'P' },
      { no: 13, nis: 'BP.26-2147', name: 'Ignacia Agustina Salsabilah', gender: 'P' },
      { no: 14, nis: 'BP.26-2148', name: 'Ilham Rasyid Widiyanto', gender: 'L' },
      { no: 15, nis: 'BP.26-2149', name: 'Jezyca Ferdiani', gender: 'P' },
      { no: 16, nis: 'BP.26-2150', name: 'Keyza Felly Devina', gender: 'P' },
      { no: 17, nis: 'BP.26-2151', name: 'Muhammad Nuzil Mubarok', gender: 'L' },
      { no: 18, nis: 'BP.26-2152', name: 'Muhammad Rafli', gender: 'L' },
      { no: 19, nis: 'BP.26-2153', name: 'Muhammad Revan Syah', gender: 'L' },
      { no: 20, nis: 'BP.26-2154', name: 'Mukhamad Rizky Putra Tritama', gender: 'L' },
      { no: 21, nis: 'BP.26-2155', name: 'Naifah Nadila', gender: 'P' },
      { no: 22, nis: 'BP.26-2156', name: 'Nazwa Putri Anisa Ramadhani', gender: 'P' },
      { no: 23, nis: 'BP.26-2157', name: 'Novita Kusuma Wardani', gender: 'P' },
      { no: 24, nis: 'BP.26-2158', name: 'Rindha Dwi Cahyaningrum', gender: 'P' },
      { no: 25, nis: 'BP.26-2159', name: 'Riska Ayuandini', gender: 'P' },
      { no: 26, nis: 'BP.26-2160', name: 'Sela Anggun Setiani', gender: 'P' },
      { no: 27, nis: 'BP.26-2161', name: 'Selma Hani Yaffa', gender: 'P' },
      { no: 28, nis: 'BP.26-2162', name: 'Shea Eka Putri Cahyani', gender: 'P' },
      { no: 29, nis: 'BP.26-2163', name: 'Sheryl Apriliyani', gender: 'P' },
      { no: 30, nis: 'BP.26-2164', name: 'Suci Exza Setianingrum', gender: 'P' },
      { no: 31, nis: 'BP.26-2165', name: 'Tegar Setiya Wicaksana', gender: 'L' },
      { no: 32, nis: 'BP.26-2166', name: 'Vanesa Oktalifa', gender: 'P' },
      { no: 33, nis: 'BP.26-2167', name: 'Vika Setia Mutiyani', gender: 'P' },
      { no: 34, nis: 'BP.26-2168', name: 'Zafian Khoiril Ahmad', gender: 'L' },
      { no: 35, nis: 'BP.26-2169', name: 'Zivana Putri Andini', gender: 'P' },
      { no: 36, nis: 'BP.26-2170', name: 'Zulfati Nirma Nadha', gender: 'P' }
    ]
  },
  // 8. X-DKV-1 (Page 8)
  {
    classKey: 'X-DKV-1',
    className: 'X-DKV-1',
    level: 'X',
    majorCode: 'DKV',
    majorName: 'Desain Komunikasi Visual',
    rombel: 1,
    homeroomTeacherName: "Muhammad Faridul Mu'arif, S.Pd.",
    maleCount: 11,
    femaleCount: 25,
    totalCount: 36,
    students: [
      { no: 1, nis: 'DKV.26-0891', name: 'Aditya David Nugroho', gender: 'L' },
      { no: 2, nis: 'DKV.26-0892', name: 'Akhsainna Jasmine Humaira', gender: 'P' },
      { no: 3, nis: 'DKV.26-0893', name: 'Allisya Putri Azzaliya', gender: 'P' },
      { no: 4, nis: 'DKV.26-0894', name: 'Anita Restu Rahayu', gender: 'P' },
      { no: 5, nis: 'DKV.26-0895', name: "Arifah Hilmi Atha ' Ullah", gender: 'P' },
      { no: 6, nis: 'DKV.26-0896', name: 'Asa Sahra Akbar', gender: 'L' },
      { no: 7, nis: 'DKV.26-0897', name: 'Banon Qurota Iqfara', gender: 'P' },
      { no: 8, nis: 'DKV.26-0898', name: 'Barirta Iswara Aliyah', gender: 'P' },
      { no: 9, nis: 'DKV.26-0899', name: 'Callista Adila Kartikasari', gender: 'P' },
      { no: 10, nis: 'DKV.26-0900', name: 'Davin Abhinaya Bilfaqih', gender: 'L' },
      { no: 11, nis: 'DKV.26-0901', name: 'Dina Maryam', gender: 'P' },
      { no: 12, nis: 'DKV.26-0902', name: "Faqira Alifatu' Zhafifah", gender: 'P' },
      { no: 13, nis: 'DKV.26-0903', name: 'Firmansyah Ibnu Rizkiyanto', gender: 'L' },
      { no: 14, nis: 'DKV.26-0904', name: 'Inawati Setya Ningrum', gender: 'P' },
      { no: 15, nis: 'DKV.26-0905', name: 'Keysha Tithania Khafid', gender: 'P' },
      { no: 16, nis: 'DKV.26-0906', name: 'Kharisma Chika Regina Putri', gender: 'P' },
      { no: 17, nis: 'DKV.26-0907', name: 'Kidung Nacinta', gender: 'P' },
      { no: 18, nis: 'DKV.26-0908', name: 'Muhammad Fadhil Fernanda', gender: 'L' },
      { no: 19, nis: 'DKV.26-0909', name: 'Muhammad Rasya Khoirul Azam', gender: 'L' },
      { no: 20, nis: 'DKV.26-0910', name: 'Nada Salsabila', gender: 'P' },
      { no: 21, nis: 'DKV.26-0911', name: 'Nadhirah Muwaffaqoh', gender: 'P' },
      { no: 22, nis: 'DKV.26-0912', name: 'Naely Zakiah', gender: 'P' },
      { no: 23, nis: 'DKV.26-0913', name: 'Nasywa Putri Amalia', gender: 'P' },
      { no: 24, nis: 'DKV.26-0914', name: 'Putri Nur Laila', gender: 'P' },
      { no: 25, nis: 'DKV.26-0915', name: 'Putri Wahyu Lestari', gender: 'P' },
      { no: 26, nis: 'DKV.26-0916', name: 'Raditya Putra Karunia', gender: 'L' },
      { no: 27, nis: 'DKV.26-0917', name: 'Rafa Iqbal Maulana', gender: 'L' },
      { no: 28, nis: 'DKV.26-0918', name: 'Revano Kairul Iksan', gender: 'L' },
      { no: 29, nis: 'DKV.26-0919', name: 'Rifatul Khasanah', gender: 'P' },
      { no: 30, nis: 'DKV.26-0920', name: 'Ririn', gender: 'P' },
      { no: 31, nis: 'DKV.26-0921', name: 'Rizky Arif Putra', gender: 'L' },
      { no: 32, nis: 'DKV.26-0922', name: 'Sagita Dewi Nurmala', gender: 'P' },
      { no: 33, nis: 'DKV.26-0923', name: 'Sellvia Anglelita', gender: 'P' },
      { no: 34, nis: 'DKV.26-0924', name: 'Senja Desita Rahmawati', gender: 'P' },
      { no: 35, nis: 'DKV.26-0925', name: 'Trisnina Arum Ramadhani', gender: 'P' },
      { no: 36, nis: 'DKV.26-0926', name: 'Wildan Muhammad Fahluzi', gender: 'L' }
    ]
  },
  // 9. X-DKV-2 (Page 9)
  {
    classKey: 'X-DKV-2',
    className: 'X-DKV-2',
    level: 'X',
    majorCode: 'DKV',
    majorName: 'Desain Komunikasi Visual',
    rombel: 2,
    homeroomTeacherName: 'Erti Santriyani Amawati, S.Pd.',
    maleCount: 20,
    femaleCount: 16,
    totalCount: 36,
    students: [
      { no: 1, nis: 'DKV.26-0927', name: 'Adam Destasetyo Sasongko', gender: 'L' },
      { no: 2, nis: 'DKV.26-0928', name: 'Adinda Saputri Ningrum', gender: 'P' },
      { no: 3, nis: 'DKV.26-0929', name: 'Ahmad Alfin Putra', gender: 'L' },
      { no: 4, nis: 'DKV.26-0930', name: 'Ahmad Kevin Pugung Sanjaya', gender: 'L' },
      { no: 5, nis: 'DKV.26-0931', name: 'Ainun Dila Wijayanti', gender: 'P' },
      { no: 6, nis: 'DKV.26-0932', name: 'Aivi Titik Indriana', gender: 'P' },
      { no: 7, nis: 'DKV.26-0933', name: 'Arifatussalma Syahida', gender: 'P' },
      { no: 8, nis: 'DKV.26-0934', name: 'Ayu Isfi Nur Maulida', gender: 'P' },
      { no: 9, nis: 'DKV.26-0935', name: 'Azahra Anindya Putri', gender: 'P' },
      { no: 10, nis: 'DKV.26-0936', name: 'Azka Nafathan Adam', gender: 'L' },
      { no: 11, nis: 'DKV.26-0937', name: 'Elang Maulana Anwar', gender: 'L' },
      { no: 12, nis: 'DKV.26-0938', name: 'Elysa Fatmayanti', gender: 'P' },
      { no: 13, nis: 'DKV.26-0939', name: 'Farid Hasyim Djazuli', gender: 'L' },
      { no: 14, nis: 'DKV.26-0940', name: 'Ferisqo Herbilatul Sabil', gender: 'L' },
      { no: 15, nis: 'DKV.26-0941', name: 'Galuh Cipto Prayogo', gender: 'L' },
      { no: 16, nis: 'DKV.26-0942', name: 'Intan Faradila Sukma', gender: 'P' },
      { no: 17, nis: 'DKV.26-0943', name: 'Javier Naufal Prasetyana', gender: 'L' },
      { no: 18, nis: 'DKV.26-0944', name: 'Kevin Surya Dwi Nugroho', gender: 'L' },
      { no: 19, nis: 'DKV.26-0945', name: 'Keyzza Rahma Aulia Azizah', gender: 'P' },
      { no: 20, nis: 'DKV.26-0946', name: 'Muchammad Ghufron Murdandi', gender: 'L' },
      { no: 21, nis: 'DKV.26-0947', name: 'Muhamad Fahri', gender: 'L' },
      { no: 22, nis: 'DKV.26-0949', name: 'Muhamad Rayhan Aditya', gender: 'L' },
      { no: 23, nis: 'DKV.26-0948', name: 'Muhammad Anahel Dany Pratama', gender: 'L' },
      { no: 24, nis: 'DKV.26-0950', name: 'Nabila Arijatul Asfa', gender: 'P' },
      { no: 25, nis: 'DKV.26-0951', name: 'Naufal Putra Pratama', gender: 'L' },
      { no: 26, nis: 'DKV.26-0952', name: 'Okta Nur Azizah', gender: 'P' },
      { no: 27, nis: 'DKV.26-0953', name: 'Rachel Rere Bintang Juwita', gender: 'P' },
      { no: 28, nis: 'DKV.26-0954', name: 'Rafael Vico Pratama', gender: 'L' },
      { no: 29, nis: 'DKV.26-0955', name: 'Raffa Maulana Irsyad', gender: 'L' },
      { no: 30, nis: 'DKV.26-0956', name: 'Saskia Maulida Cahya Wati', gender: 'P' },
      { no: 31, nis: 'DKV.26-0957', name: 'Satria Arya Yuda', gender: 'L' },
      { no: 32, nis: 'DKV.26-0958', name: 'Syahda Tsania Khoirunnisa', gender: 'P' },
      { no: 33, nis: 'DKV.26-0959', name: 'Tharaa Qonita', gender: 'P' },
      { no: 34, nis: 'DKV.26-0960', name: 'Wahyu Layla Aprilia Putri', gender: 'P' },
      { no: 35, nis: 'DKV.26-0961', name: 'Wahyu Setyawan', gender: 'L' },
      { no: 36, nis: 'DKV.26-0962', name: "Zihaq Nur A'sikin Habban", gender: 'L' }
    ]
  },
  // 10. X-DKV-3 (Page 10)
  {
    classKey: 'X-DKV-3',
    className: 'X-DKV-3',
    level: 'X',
    majorCode: 'DKV',
    majorName: 'Desain Komunikasi Visual',
    rombel: 3,
    homeroomTeacherName: "Nisa'ul Lathifatul Khoir, S.Pd., M.Pd.",
    maleCount: 22,
    femaleCount: 13,
    totalCount: 35,
    students: [
      { no: 1, nis: 'DKV.26-0963', name: 'Aidil Faza Akbar', gender: 'L' },
      { no: 2, nis: 'DKV.26-0964', name: 'Alika Dwi Silfiani', gender: 'P' },
      { no: 3, nis: 'DKV.26-0965', name: 'Azil Adistrian', gender: 'L' },
      { no: 4, nis: 'DKV.26-0966', name: 'Claresta Johanna Alya Mukhbita', gender: 'P' },
      { no: 5, nis: 'DKV.26-0967', name: 'Danang Fitri', gender: 'L' },
      { no: 6, nis: 'DKV.26-0968', name: 'Della Selvy Virgiana', gender: 'P' },
      { no: 7, nis: 'DKV.26-0969', name: 'Deviana Chanda Kasih', gender: 'P' },
      { no: 8, nis: 'DKV.26-0970', name: "Eka Rofi'atun Khasanah", gender: 'P' },
      { no: 9, nis: 'DKV.25-0828', name: 'Elbanez Yuan Fitra', gender: 'L' },
      { no: 10, nis: 'DKV.26-0973', name: 'Habib Khoerul Azzam', gender: 'L' },
      { no: 11, nis: 'DKV.26-0975', name: 'Irfan Agus Nursalim', gender: 'L' },
      { no: 12, nis: 'DKV.26-0976', name: 'Jazil Nauva Asfiyana', gender: 'P' },
      { no: 13, nis: 'DKV.26-0977', name: 'Julie Syafia Kinara', gender: 'P' },
      { no: 14, nis: 'DKV.26-0978', name: 'Kenzie Taftazani Akmal', gender: 'L' },
      { no: 15, nis: 'DKV.26-0979', name: 'Kirana Meisyita Agna Bela', gender: 'P' },
      { no: 16, nis: 'DKV.26-0980', name: 'Maulida Salsabila Leilani', gender: 'P' },
      { no: 17, nis: 'DKV.26-0987', name: 'Muhamad Helga Ocktaviano', gender: 'L' },
      { no: 18, nis: 'DKV.26-0982', name: 'Muhamad Nizar Al-Ghifari', gender: 'L' },
      { no: 19, nis: 'DKV.26-0983', name: 'Muhamad Syahrul Alim', gender: 'L' },
      { no: 20, nis: 'DKV.26-0984', name: 'Muhammad Alvin Pradana', gender: 'L' },
      { no: 21, nis: 'DKV.26-0985', name: 'Muhammad Farhan Hamdani', gender: 'L' },
      { no: 22, nis: 'DKV.26-0986', name: 'Muhammad Fariz Rosyiqul Ahnaf', gender: 'L' },
      { no: 23, nis: 'DKV.26-0981', name: 'Muhammad Irvan', gender: 'L' },
      { no: 24, nis: 'DKV.26-0999', name: 'Muhammad Zakki Munawwar', gender: 'L' },
      { no: 25, nis: 'DKV.26-0988', name: 'Nugroho Saktiawan', gender: 'L' },
      { no: 26, nis: 'DKV.26-0989', name: 'Pungkas Tegar Utomo', gender: 'L' },
      { no: 27, nis: 'DKV.26-0990', name: 'Putra Nito Davin Pratama', gender: 'L' },
      { no: 28, nis: 'DKV.26-0991', name: "Qosiyatus Sa'diyah", gender: 'P' },
      { no: 29, nis: 'DKV.26-0992', name: 'Quinzha Adhellia Thazmira Respati', gender: 'P' },
      { no: 30, nis: 'DKV.26-0993', name: 'Revan Julio Putra', gender: 'L' },
      { no: 31, nis: 'DKV.26-0994', name: 'Ridwan Yoga Kurniawan', gender: 'L' },
      { no: 32, nis: 'DKV.26-0995', name: 'Septi Zulfiani', gender: 'P' },
      { no: 33, nis: 'DKV.26-0996', name: 'Ulil Hamzah Risqy Wibisono', gender: 'L' },
      { no: 34, nis: 'DKV.26-0997', name: 'Vanessa Putri', gender: 'P' },
      { no: 35, nis: 'DKV.26-0998', name: 'Vino Arya Ramadian', gender: 'L' }
    ]
  },
  // 11. X-TE-1 (Page 11)
  {
    classKey: 'X-TE-1',
    className: 'X-TE-1',
    level: 'X',
    majorCode: 'TE',
    majorName: 'Teknik Elektronika',
    rombel: 1,
    homeroomTeacherName: 'Much Roisul Mahiruddin, S.Pd.',
    maleCount: 35,
    femaleCount: 0,
    totalCount: 35,
    students: [
      { no: 1, nis: 'TE.26-0724', name: 'Abi Tsamrotul Qolbis Salim', gender: 'L' },
      { no: 2, nis: 'TE.26-0725', name: 'Achmad Rozyqien', gender: 'L' },
      { no: 3, nis: 'TE.26-0726', name: 'Ahmad Taufiqul Hakim', gender: 'L' },
      { no: 4, nis: 'TE.26-0727', name: 'Aldi Arya Pratama', gender: 'L' },
      { no: 5, nis: 'TE.26-0728', name: 'Andika Ahmad Taufiq', gender: 'L' },
      { no: 6, nis: 'TE.26-0729', name: 'Ardefa Rega Wijaya', gender: 'L' },
      { no: 7, nis: 'TE.26-0730', name: 'Arjuna Al Farobi Muhamad', gender: 'L' },
      { no: 8, nis: 'TE.26-0731', name: 'Audrey Rifqi Ewaldo', gender: 'L' },
      { no: 9, nis: 'TE.26-0732', name: 'Aunan Lanafinaja', gender: 'L' },
      { no: 10, nis: 'TE.26-0733', name: 'Azriel Dafa Maulana', gender: 'L' },
      { no: 11, nis: 'TE.26-0734', name: 'Bentar Muhamad Mahatari', gender: 'L' },
      { no: 12, nis: 'TE.26-0735', name: 'Cakrawangsa Taj Al Jinan', gender: 'L' },
      { no: 13, nis: 'TE.26-0736', name: 'Diara Helga Arsa', gender: 'L' },
      { no: 14, nis: 'TE.26-0737', name: 'Dwi Putra Andika', gender: 'L' },
      { no: 15, nis: 'TE.26-0738', name: 'Ega Cesar Dwi Permana', gender: 'L' },
      { no: 16, nis: 'TE.26-0739', name: 'Fadhil Raditya Mukti Hidayat', gender: 'L' },
      { no: 17, nis: 'TE.26-0740', name: 'Fahmi Fatkhurozi', gender: 'L' },
      { no: 18, nis: 'TE.26-0834', name: 'Hasan Wira Silaen', gender: 'L' },
      { no: 19, nis: 'TE.26-0741', name: 'Irfan Nanda Prasetya', gender: 'L' },
      { no: 20, nis: 'TE.26-0742', name: 'Jalil Kholilullah', gender: 'L' },
      { no: 21, nis: 'TE.26-0743', name: 'Krisna Irghi Hermawan', gender: 'L' },
      { no: 22, nis: 'TE.26-0745', name: 'Mahandika Yusuf Wibisono', gender: 'L' },
      { no: 23, nis: 'TE.26-0747', name: 'Muhamad Abdilah Megantoro', gender: 'L' },
      { no: 24, nis: 'TE.26-0748', name: 'Muhamad Mahreza Rizqi Firmansah', gender: 'L' },
      { no: 25, nis: 'TE.26-0749', name: 'Muhammad Faiz Hamdany', gender: 'L' },
      { no: 26, nis: 'TE.26-0750', name: 'Muhammad Haikal Dzammares Al Zahir', gender: 'L' },
      { no: 27, nis: 'TE.26-0751', name: 'Muhammad Haikal Febri Anugrah', gender: 'L' },
      { no: 28, nis: 'TE.26-0833', name: 'Muhammad Kenzie Herald Maritza', gender: 'L' },
      { no: 29, nis: 'TE.26-0752', name: 'Noval Gigih Kurnia', gender: 'L' },
      { no: 30, nis: 'TE.26-0753', name: 'Pungkas Wahyu Hizqi Fahrezi', gender: 'L' },
      { no: 31, nis: 'TE.26-0755', name: 'Saputra Ardhi Wibowo', gender: 'L' },
      { no: 32, nis: 'TE.26-0756', name: 'Yodha Poernomo', gender: 'L' },
      { no: 33, nis: 'TE.26-0757', name: 'Yongky Villa Kurniawan', gender: 'L' },
      { no: 34, nis: 'TE.26-0758', name: 'Zaky Khoirul Anam', gender: 'L' },
      { no: 35, nis: 'TE.26-0759', name: 'Zoppi Alfitra Raya', gender: 'L' }
    ]
  },
  // 12. X-TE-2 (Page 12)
  {
    classKey: 'X-TE-2',
    className: 'X-TE-2',
    level: 'X',
    majorCode: 'TE',
    majorName: 'Teknik Elektronika',
    rombel: 2,
    homeroomTeacherName: 'Ikbal Saputra, S.Pd.',
    maleCount: 35,
    femaleCount: 0,
    totalCount: 35,
    students: [
      { no: 1, nis: 'TE.26-0760', name: 'Ahmad Ridho Maulana', gender: 'L' },
      { no: 2, nis: 'TE.26-0761', name: 'Aldo Arya Prastyo', gender: 'L' },
      { no: 3, nis: 'TE.26-0762', name: 'Aldo Cahya Ramadhani', gender: 'L' },
      { no: 4, nis: 'TE.26-0763', name: 'Alfarizzi Azka Yusuf Saputra', gender: 'L' },
      { no: 5, nis: 'TE.26-0765', name: 'Arya Cahya Mahardika', gender: 'L' },
      { no: 6, nis: 'TE.26-0764', name: 'Auqila Zaeni Muhtar', gender: 'L' },
      { no: 7, nis: 'TE.26-0766', name: 'Azril Zhorif Yuwanida', gender: 'L' },
      { no: 8, nis: 'TE.26-0767', name: 'Bili Erfin Pratama', gender: 'L' },
      { no: 9, nis: 'TE.26-0768', name: 'Daffa Dwi Yuliyanto', gender: 'L' },
      { no: 10, nis: 'TE.26-0769', name: 'Destha Al Friansyah', gender: 'L' },
      { no: 11, nis: 'TE.26-0770', name: 'Dirly Alfino Putra', gender: 'L' },
      { no: 12, nis: 'TE.26-0771', name: 'Erick Fernandho', gender: 'L' },
      { no: 13, nis: 'TE.26-0772', name: 'Eudora Gavra Argya', gender: 'L' },
      { no: 14, nis: 'TE.26-0773', name: 'Fajar Nur Rohman', gender: 'L' },
      { no: 15, nis: 'TE.26-0774', name: 'Farid Nurhidayat', gender: 'L' },
      { no: 16, nis: 'TE.26-0775', name: 'Fariz Azka Rafi', gender: 'L' },
      { no: 17, nis: 'TE.26-0776', name: 'Hafizh Okta Dwi Saputra', gender: 'L' },
      { no: 18, nis: 'TE.26-0777', name: 'Ibnu Syabil Ramadhani', gender: 'L' },
      { no: 19, nis: 'TE.26-0778', name: 'Lanang Pratista Argani', gender: 'L' },
      { no: 20, nis: 'TE.26-0779', name: 'Muhamad Affan', gender: 'L' },
      { no: 21, nis: 'TE.26-0781', name: 'Muhamad Andika Yoga Kusuma', gender: 'L' },
      { no: 22, nis: 'TE.26-0786', name: 'Muhamad Yusuf Mansur', gender: 'L' },
      { no: 23, nis: 'TE.26-0782', name: "Muhammad Azzam Fa'id", gender: 'L' },
      { no: 24, nis: 'TE.26-0832', name: 'Muhammad Farid', gender: 'L' },
      { no: 25, nis: 'TE.26-0780', name: 'Muhammad Resa Anggiawan', gender: 'L' },
      { no: 26, nis: 'TE.26-0783', name: 'Muhammad Rizky Ardiansyah', gender: 'L' },
      { no: 27, nis: 'TE.26-0784', name: 'Muhammad Ryuzaki Satriani', gender: 'L' },
      { no: 28, nis: 'TE.26-0787', name: 'Najmi Rayyan Haikal Alfreda', gender: 'L' },
      { no: 29, nis: 'TE.26-0788', name: 'Okta Nauval Hidayat', gender: 'L' },
      { no: 30, nis: 'TE.26-0789', name: 'Rafa Enggar Saputra', gender: 'L' },
      { no: 31, nis: 'TE.26-0790', name: 'Rafael Gilang Satria', gender: 'L' },
      { no: 32, nis: 'TE.26-0791', name: 'Rahmad Syahbani Ibnu Ahya Uddin', gender: 'L' },
      { no: 33, nis: 'TE.26-0792', name: 'Rakha Ardianto', gender: 'L' },
      { no: 34, nis: 'TE.26-0793', name: 'Rendy Triyanto', gender: 'L' },
      { no: 35, nis: 'TE.26-0794', name: 'Revan Nasrullah', gender: 'L' }
    ]
  },
  // 13. X-TE-3 (Page 13)
  {
    classKey: 'X-TE-3',
    className: 'X-TE-3',
    level: 'X',
    majorCode: 'TE',
    majorName: 'Teknik Elektronika',
    rombel: 3,
    homeroomTeacherName: 'Nur Arifah, S.Pd.',
    maleCount: 36,
    femaleCount: 0,
    totalCount: 36,
    students: [
      { no: 1, nis: 'TE.26-0796', name: 'Alief Arsyadany', gender: 'L' },
      { no: 2, nis: 'TE.26-0797', name: 'Andres Rafasatya', gender: 'L' },
      { no: 3, nis: 'TE.26-0798', name: 'Aqim Miftahudin', gender: 'L' },
      { no: 4, nis: 'TE.26-0799', name: 'Arfan Fatkhul Afrian', gender: 'L' },
      { no: 5, nis: 'TE.26-0800', name: 'Arkhan Fais Assyafi', gender: 'L' },
      { no: 6, nis: 'TE.26-0801', name: 'Atharizz Calief Muhammad', gender: 'L' },
      { no: 7, nis: 'TE.26-0802', name: 'Azief Irfan Maulana', gender: 'L' },
      { no: 8, nis: 'TE.26-0803', name: 'Aziel Rafid Akbar', gender: 'L' },
      { no: 9, nis: 'TE.26-0804', name: 'Bima Rusdiyanto', gender: 'L' },
      { no: 10, nis: 'TE.26-0805', name: 'Desta Nur Huda', gender: 'L' },
      { no: 11, nis: 'TE.26-0806', name: 'Dhanex Wahyutomo', gender: 'L' },
      { no: 12, nis: 'TE.26-0807', name: 'Erlang Duta Permana', gender: 'L' },
      { no: 13, nis: 'TE.26-0808', name: 'Fardan Fajar Al Adam', gender: 'L' },
      { no: 14, nis: 'TE.26-0809', name: 'Febriandika Rizky Diwah Pratama', gender: 'L' },
      { no: 15, nis: 'TE.26-0810', name: 'Hafiidl Riskia Putra', gender: 'L' },
      { no: 16, nis: 'TE.26-0811', name: 'Hafiyan Azka Putra Pratama', gender: 'L' },
      { no: 17, nis: 'TE.26-0812', name: 'Ilham Ragil Putra Hardasyah', gender: 'L' },
      { no: 18, nis: 'TE.26-0813', name: 'Jadhug Satrio Negoro', gender: 'L' },
      { no: 19, nis: 'TE.26-0814', name: 'Kevin Keandra Ibrahim', gender: 'L' },
      { no: 20, nis: 'TE.26-0815', name: 'Maulidhil Dafa Pratama', gender: 'L' },
      { no: 21, nis: 'TE.26-0816', name: 'Muchammad Haikal Ashomadani Nugroho', gender: 'L' },
      { no: 22, nis: 'TE.26-0817', name: 'Muhammad Imam Saputra', gender: 'L' },
      { no: 23, nis: 'TE.26-0818', name: 'Muhammad Qullumuddin', gender: 'L' },
      { no: 24, nis: 'TE.26-0819', name: 'Muhammad Rezzel Alfarisy', gender: 'L' },
      { no: 25, nis: 'TE.26-0820', name: 'Nizar Hafizh Issaniansyah', gender: 'L' },
      { no: 26, nis: 'TE.26-0821', name: 'Oktavio Maulana', gender: 'L' },
      { no: 27, nis: 'TE.26-0822', name: 'One Srila Ebyth Dava', gender: 'L' },
      { no: 28, nis: 'TE.26-0823', name: 'Priyo Setyo Utomo', gender: 'L' },
      { no: 29, nis: 'TE.26-0824', name: 'Raevan Putra Fahrezi', gender: 'L' },
      { no: 30, nis: 'TE.26-0825', name: 'Reyvino Adyatma Fadhil', gender: 'L' },
      { no: 31, nis: 'TE.26-0826', name: 'Rezada Kafka Luis', gender: 'L' },
      { no: 32, nis: 'TE.26-0827', name: 'Ridwan Syahreza', gender: 'L' },
      { no: 33, nis: 'TE.26-0828', name: 'Riko Aditya Putra', gender: 'L' },
      { no: 34, nis: 'TE.26-0829', name: 'Rizki Nugroho', gender: 'L' },
      { no: 35, nis: 'TE.26-0830', name: 'Shafwan Hablun Ardiyanto', gender: 'L' },
      { no: 36, nis: 'TE.26-0831', name: 'Wildan Hamka Asadea', gender: 'L' }
    ]
  },
  // 14. X-TO-1 (Page 14)
  {
    classKey: 'X-TO-1',
    className: 'X-TO-1',
    level: 'X',
    majorCode: 'TO',
    majorName: 'Teknik Otomotif',
    rombel: 1,
    homeroomTeacherName: 'Nur Suciati, S.Pd.',
    maleCount: 36,
    femaleCount: 0,
    totalCount: 36,
    students: [
      { no: 1, nis: 'TO.26-0854', name: 'Aditia Gemilang Permana', gender: 'L' },
      { no: 2, nis: 'TO.26-0855', name: 'Ahmad Alvaro Tankiansyah', gender: 'L' },
      { no: 3, nis: 'TO.26-0856', name: 'Ahmad Fajar Nugroho', gender: 'L' },
      { no: 4, nis: 'TO.26-0857', name: 'Ananda Egi Saputra', gender: 'L' },
      { no: 5, nis: 'TO.26-0858', name: 'Arvi Umar Kurniawan', gender: 'L' },
      { no: 6, nis: 'TO.26-0859', name: 'Azam Maulida Akhmad', gender: 'L' },
      { no: 7, nis: 'TO.26-0860', name: 'Danadyaksa Kaka Maheswara', gender: 'L' },
      { no: 8, nis: 'TO.26-0861', name: 'Dirga Aji Bramantyo', gender: 'L' },
      { no: 9, nis: 'TO.26-0862', name: 'Dwi Putra Arya Guna', gender: 'L' },
      { no: 10, nis: 'TO.26-0863', name: 'Evan Hazza Harnanto', gender: 'L' },
      { no: 11, nis: 'TO.26-0864', name: 'Fabrian Kafka Rizky Adhim', gender: 'L' },
      { no: 12, nis: 'TO.26-0865', name: 'Faisal Dwi Satria', gender: 'L' },
      { no: 13, nis: 'TO.26-0866', name: 'Faruq Dwi Setiyawan', gender: 'L' },
      { no: 14, nis: 'TO.26-0867', name: 'Hendra Setyo Nugroho', gender: 'L' },
      { no: 15, nis: 'TO.26-0868', name: 'Iqbal Fathian', gender: 'L' },
      { no: 16, nis: 'TO.26-0869', name: 'Izaan Azbin Farrand', gender: 'L' },
      { no: 17, nis: 'TO.26-0870', name: 'Julio Haidar Daniswara', gender: 'L' },
      { no: 18, nis: 'TO.26-0872', name: 'Muhamad Aksza Sigit Pramana', gender: 'L' },
      { no: 19, nis: 'TO.26-0873', name: 'Muhammad Alvin Eka Saputra', gender: 'L' },
      { no: 20, nis: 'TO.26-0871', name: 'Muhammad Febriandika Saputra', gender: 'L' },
      { no: 21, nis: 'TO.26-0874', name: 'Muhammad Ghufron', gender: 'L' },
      { no: 22, nis: 'TO.26-0875', name: 'Muhammad Vino Dwi Ramadhan', gender: 'L' },
      { no: 23, nis: 'TO.26-0876', name: 'Muhammad Wisnu Anugrah', gender: 'L' },
      { no: 24, nis: 'TO.26-0877', name: 'Oktaviano Ajinuli Rahayu', gender: 'L' },
      { no: 25, nis: 'TO.26-0878', name: 'Pradipa Atha Syandana', gender: 'L' },
      { no: 26, nis: 'TO.26-0879', name: 'Rafa Galih Alvian', gender: 'L' },
      { no: 27, nis: 'TO.26-0880', name: 'Rafqizi Souma Abimanyu', gender: 'L' },
      { no: 28, nis: 'TO.26-0881', name: 'Raka Ruwa Uha', gender: 'L' },
      { no: 29, nis: 'TO.26-0882', name: 'Rendy Setiyawan', gender: 'L' },
      { no: 30, nis: 'TO.26-0883', name: 'Revan Pandu Saputra', gender: 'L' },
      { no: 31, nis: 'TO.26-0884', name: 'Septa Tri Hertyas Ramadhan', gender: 'L' },
      { no: 32, nis: 'TO.26-0885', name: 'Septian Dwi Ramdhani', gender: 'L' },
      { no: 33, nis: 'TO.26-0886', name: 'Tunas Haska Prayoga', gender: 'L' },
      { no: 34, nis: 'TO.26-0887', name: 'Vino Novian Akbar', gender: 'L' },
      { no: 35, nis: 'TO.26-0888', name: 'Wahyu Nurohman', gender: 'L' },
      { no: 36, nis: 'TO.26-0889', name: 'Wildan Ardiansyah', gender: 'L' }
    ]
  },
  // 15. X-TO-2 (Page 15)
  {
    classKey: 'X-TO-2',
    className: 'X-TO-2',
    level: 'X',
    majorCode: 'TO',
    majorName: 'Teknik Otomotif',
    rombel: 2,
    homeroomTeacherName: 'Rita Rianti, S.Pd.',
    maleCount: 36,
    femaleCount: 0,
    totalCount: 36,
    students: [
      { no: 1, nis: 'TO.26-0890', name: 'Adly Putra Fahreza', gender: 'L' },
      { no: 2, nis: 'TO.26-0891', name: 'Afpri Rohmat Soleh', gender: 'L' },
      { no: 3, nis: 'TO.26-0892', name: 'Ahmad Firdaus', gender: 'L' },
      { no: 4, nis: 'TO.26-0893', name: 'Ahmad Ibnu Khajar', gender: 'L' },
      { no: 5, nis: 'TO.26-0894', name: 'Ahmad Syarif Maulana', gender: 'L' },
      { no: 6, nis: 'TO.26-0895', name: 'Ahnaf Akbar Dwi Saputra', gender: 'L' },
      { no: 7, nis: 'TO.26-0896', name: 'Ahya Nova Yulianto', gender: 'L' },
      { no: 8, nis: 'TO.26-0897', name: 'Alfino Dwi Rianto', gender: 'L' },
      { no: 9, nis: 'TO.26-0898', name: 'Alvian Dian Saputra', gender: 'L' },
      { no: 10, nis: 'TO.26-0899', name: 'Aran Widiyatmoko', gender: 'L' },
      { no: 11, nis: 'TO.26-0900', name: 'Arka Naufal Rifky Afriel', gender: 'L' },
      { no: 12, nis: 'TO.26-0901', name: 'Arya Ilham Saputra', gender: 'L' },
      { no: 13, nis: 'TO.26-0902', name: 'Az Ziggi Maulana', gender: 'L' },
      { no: 14, nis: 'TO.26-0903', name: 'Fachri Chabibi Tsani Albariq', gender: 'L' },
      { no: 15, nis: 'TO.26-0904', name: 'Fadha Fatkhurohman', gender: 'L' },
      { no: 16, nis: 'TO.26-0905', name: 'Fahmi Sahlan Nurendra', gender: 'L' },
      { no: 17, nis: 'TO.26-0906', name: 'Fauzan Tirta Maulana Kamil', gender: 'L' },
      { no: 18, nis: 'TO.26-0907', name: 'Firja Afif Saputra', gender: 'L' },
      { no: 19, nis: 'TO.26-0908', name: 'Jaffar Rezqi Ramadhan', gender: 'L' },
      { no: 20, nis: 'TO.26-0909', name: 'Juliyan Abidin', gender: 'L' },
      { no: 21, nis: 'TO.26-0910', name: 'Khanif Muhamad Azam', gender: 'L' },
      { no: 22, nis: 'TO.26-0911', name: 'Khoerul Umur Ausatuha', gender: 'L' },
      { no: 23, nis: 'TO.26-0912', name: 'Maulana Arga Al Dhamarullah', gender: 'L' },
      { no: 24, nis: 'TO.26-0913', name: 'Maulana Fadlikal Adzimi', gender: 'L' },
      { no: 25, nis: 'TO.26-0914', name: 'Maulana Kevin Saputra', gender: 'L' },
      { no: 26, nis: 'TO.26-0915', name: 'Muhammad Afifullah At-Tauhid', gender: 'L' },
      { no: 27, nis: 'TO.26-0916', name: 'Muhammad Azriel Yudistira', gender: 'L' },
      { no: 28, nis: 'TO.26-0917', name: 'Muhammad Rosyid Ilham', gender: 'L' },
      { no: 29, nis: 'TO.26-0918', name: 'Noer Rizki Saputra', gender: 'L' },
      { no: 30, nis: 'TO.26-0919', name: 'Novaldy Wisnu Pratama', gender: 'L' },
      { no: 31, nis: 'TO.26-0920', name: 'Ravi Nur Rohman', gender: 'L' },
      { no: 32, nis: 'TO.26-0921', name: 'Robby Firman Maulana', gender: 'L' },
      { no: 33, nis: 'TO.26-0922', name: 'Sandi Ramadita', gender: 'L' },
      { no: 34, nis: 'TO.26-0923', name: "Satria Nur Mu'iiz", gender: 'L' },
      { no: 35, nis: 'TO.26-0924', name: 'Shidqi Patria', gender: 'L' },
      { no: 36, nis: 'TO.26-0925', name: 'Tegar Nova Hariyanto', gender: 'L' }
    ]
  },
  // 16. X-TO-3 (Page 16)
  {
    classKey: 'X-TO-3',
    className: 'X-TO-3',
    level: 'X',
    majorCode: 'TO',
    majorName: 'Teknik Otomotif',
    rombel: 3,
    homeroomTeacherName: 'Puji Jeli Mahanani, S.Pd.',
    maleCount: 37,
    femaleCount: 0,
    totalCount: 37,
    students: [
      { no: 1, nis: 'TO.26-0926', name: 'Adam Filjinani', gender: 'L' },
      { no: 2, nis: 'TO.26-0927', name: 'Alfitroh Tegar Ramadhan', gender: 'L' },
      { no: 3, nis: 'TO.26-0928', name: 'Arga Bayuaji Pamungkas', gender: 'L' },
      { no: 4, nis: 'TO.26-0929', name: 'Arya Maulana Ahmad', gender: 'L' },
      { no: 5, nis: 'TO.26-0930', name: 'Bima Hardika', gender: 'L' },
      { no: 6, nis: 'TO.26-0931', name: 'Dafa Meigi Saputra', gender: 'L' },
      { no: 7, nis: 'TO.26-0932', name: 'Fachril Cahya Rahmadhani', gender: 'L' },
      { no: 8, nis: 'TO.26-0933', name: 'Faqih Akhmad Asyifa', gender: 'L' },
      { no: 9, nis: 'TO.26-0934', name: 'Hadika Prasetiyo', gender: 'L' },
      { no: 10, nis: 'TO.26-0935', name: 'Hafis Ardi Wijaksono', gender: 'L' },
      { no: 11, nis: 'TO.26-0936', name: 'Iqbal Andrean Saputra', gender: 'L' },
      { no: 12, nis: 'TO.26-0937', name: 'Iqbal Aufa Firmansyah', gender: 'L' },
      { no: 13, nis: 'TO.26-0938', name: 'Krishna Muchtar', gender: 'L' },
      { no: 14, nis: 'TO.26-0939', name: 'Miftakhul Arif Rahman', gender: 'L' },
      { no: 15, nis: 'TO.26-0940', name: 'Miftakhur Robik', gender: 'L' },
      { no: 16, nis: 'TO.26-0941', name: 'Mohamad Aji Prasetyo', gender: 'L' },
      { no: 17, nis: 'TO.26-0950', name: 'Muhamad Robith Nur Khaqiqi', gender: 'L' },
      { no: 18, nis: 'TO.26-0942', name: 'Muhamad Rubama Hidayatullah', gender: 'L' },
      { no: 19, nis: 'TO.26-0943', name: 'Muhammad Avif Ashar', gender: 'L' },
      { no: 20, nis: 'TO.26-0944', name: "Muhammad Badi' Ardiansyah", gender: 'L' },
      { no: 21, nis: 'TO.26-0945', name: "Muhammad Bintang Fahri Annafi'", gender: 'L' },
      { no: 22, nis: 'TO.26-0946', name: 'Muhammad Davin Andika Pratama', gender: 'L' },
      { no: 23, nis: 'TO.26-0947', name: 'Muhammad Dhahlan Khusaini', gender: 'L' },
      { no: 24, nis: 'TO.26-0948', name: 'Muhammad Firman', gender: 'L' },
      { no: 25, nis: 'TO.26-0949', name: 'Muhammad Naufal Maulana Arkan', gender: 'L' },
      { no: 26, nis: 'TO.26-0951', name: 'Muhammad Vino Irfanul Alim', gender: 'L' },
      { no: 27, nis: 'TO.26-0952', name: 'Okta Surya Ardana', gender: 'L' },
      { no: 28, nis: 'TO.26-0953', name: 'Prasetyo Nugroho', gender: 'L' },
      { no: 29, nis: 'TO.26-0954', name: 'Rafkah Arfiansyah', gender: 'L' },
      { no: 30, nis: 'TO.26-0955', name: 'Rama Arjuna Putra', gender: 'L' },
      { no: 31, nis: 'TO.26-0956', name: 'Rehan Maulana Abdi Setiawan', gender: 'L' },
      { no: 32, nis: 'TO.26-0957', name: 'Rehan Saputra Utama', gender: 'L' },
      { no: 33, nis: 'TO.26-0958', name: "Shaiful Ma'ruf", gender: 'L' },
      { no: 34, nis: 'TO.26-0959', name: 'Shindu Setyawan', gender: 'L' },
      { no: 35, nis: 'TO.26-0960', name: "Shoni Tata A'izzulhaq", gender: 'L' },
      { no: 36, nis: 'TO.26-0961', name: 'Ulul Amri Ardiansyah', gender: 'L' },
      { no: 37, nis: 'TO.26-0962', name: 'Wahyu Surya Irawan', gender: 'L' }
    ]
  }
]

/**
 * Standard definitions for Kelas XI and XII using matching school roster pattern
 */
export function getStandardLeggerRosterByLevel(level: 'X' | 'XI' | 'XII'): ClassLeggerDefinition[] {
  if (level === 'X') {
    return VERIFIED_GRADE_X_LEGGERS
  }

  // Generate standardized class legger templates for Grade XI and XII
  const classConfigs: Array<{
    rombelKey: string
    majorCode: 'TJKT' | 'BP' | 'DKV' | 'TE' | 'TO'
    majorName: string
    rombel: number
    maleCount: number
    femaleCount: number
    prefix: string
  }> =
    level === 'XI'
      ? [
          {
            rombelKey: 'XI-TJKT-1',
            majorCode: 'TJKT',
            majorName: 'Teknik Jaringan Komputer dan Telekomunikasi',
            rombel: 1,
            maleCount: 24,
            femaleCount: 11,
            prefix: 'TJKT.25'
          },
          {
            rombelKey: 'XI-TJKT-2',
            majorCode: 'TJKT',
            majorName: 'Teknik Jaringan Komputer dan Telekomunikasi',
            rombel: 2,
            maleCount: 23,
            femaleCount: 12,
            prefix: 'TJKT.25'
          },
          {
            rombelKey: 'XI-TJKT-3',
            majorCode: 'TJKT',
            majorName: 'Teknik Jaringan Komputer dan Telekomunikasi',
            rombel: 3,
            maleCount: 24,
            femaleCount: 11,
            prefix: 'TJKT.25'
          },
          {
            rombelKey: 'XI-TJKT-4',
            majorCode: 'TJKT',
            majorName: 'Teknik Jaringan Komputer dan Telekomunikasi',
            rombel: 4,
            maleCount: 23,
            femaleCount: 11,
            prefix: 'TJKT.25'
          },
          {
            rombelKey: 'XI-BP-1',
            majorCode: 'BP',
            majorName: 'Broadcasting dan Perfilman',
            rombel: 1,
            maleCount: 15,
            femaleCount: 19,
            prefix: 'BP.25'
          },
          {
            rombelKey: 'XI-BP-2',
            majorCode: 'BP',
            majorName: 'Broadcasting dan Perfilman',
            rombel: 2,
            maleCount: 15,
            femaleCount: 19,
            prefix: 'BP.25'
          },
          {
            rombelKey: 'XI-BP-3',
            majorCode: 'BP',
            majorName: 'Broadcasting dan Perfilman',
            rombel: 3,
            maleCount: 16,
            femaleCount: 18,
            prefix: 'BP.25'
          },
          {
            rombelKey: 'XI-DKV-1',
            majorCode: 'DKV',
            majorName: 'Desain Komunikasi Visual',
            rombel: 1,
            maleCount: 22,
            femaleCount: 13,
            prefix: 'DKV.25'
          },
          {
            rombelKey: 'XI-DKV-2',
            majorCode: 'DKV',
            majorName: 'Desain Komunikasi Visual',
            rombel: 2,
            maleCount: 21,
            femaleCount: 13,
            prefix: 'DKV.25'
          },
          {
            rombelKey: 'XI-DKV-3',
            majorCode: 'DKV',
            majorName: 'Desain Komunikasi Visual',
            rombel: 3,
            maleCount: 22,
            femaleCount: 13,
            prefix: 'DKV.25'
          },
          {
            rombelKey: 'XI-TE-1',
            majorCode: 'TE',
            majorName: 'Teknik Elektronika',
            rombel: 1,
            maleCount: 34,
            femaleCount: 1,
            prefix: 'TE.25'
          },
          {
            rombelKey: 'XI-TE-2',
            majorCode: 'TE',
            majorName: 'Teknik Elektronika',
            rombel: 2,
            maleCount: 34,
            femaleCount: 1,
            prefix: 'TE.25'
          },
          {
            rombelKey: 'XI-TO-1',
            majorCode: 'TO',
            majorName: 'Teknik Otomotif',
            rombel: 1,
            maleCount: 35,
            femaleCount: 1,
            prefix: 'TO.25'
          },
          {
            rombelKey: 'XI-TO-2',
            majorCode: 'TO',
            majorName: 'Teknik Otomotif',
            rombel: 2,
            maleCount: 34,
            femaleCount: 1,
            prefix: 'TO.25'
          },
          {
            rombelKey: 'XI-TO-3',
            majorCode: 'TO',
            majorName: 'Teknik Otomotif',
            rombel: 3,
            maleCount: 34,
            femaleCount: 1,
            prefix: 'TO.25'
          }
        ]
      : [
          {
            rombelKey: 'XII-TJKT-1',
            majorCode: 'TJKT',
            majorName: 'Teknik Jaringan Komputer dan Telekomunikasi',
            rombel: 1,
            maleCount: 23,
            femaleCount: 11,
            prefix: 'TJKT.24'
          },
          {
            rombelKey: 'XII-TJKT-2',
            majorCode: 'TJKT',
            majorName: 'Teknik Jaringan Komputer dan Telekomunikasi',
            rombel: 2,
            maleCount: 23,
            femaleCount: 11,
            prefix: 'TJKT.24'
          },
          {
            rombelKey: 'XII-TJKT-3',
            majorCode: 'TJKT',
            majorName: 'Teknik Jaringan Komputer dan Telekomunikasi',
            rombel: 3,
            maleCount: 23,
            femaleCount: 11,
            prefix: 'TJKT.24'
          },
          {
            rombelKey: 'XII-TJKT-4',
            majorCode: 'TJKT',
            majorName: 'Teknik Jaringan Komputer dan Telekomunikasi',
            rombel: 4,
            maleCount: 22,
            femaleCount: 11,
            prefix: 'TJKT.24'
          },
          {
            rombelKey: 'XII-BP-1',
            majorCode: 'BP',
            majorName: 'Broadcasting dan Perfilman',
            rombel: 1,
            maleCount: 10,
            femaleCount: 16,
            prefix: 'BP.24'
          },
          {
            rombelKey: 'XII-BP-2',
            majorCode: 'BP',
            majorName: 'Broadcasting dan Perfilman',
            rombel: 2,
            maleCount: 10,
            femaleCount: 16,
            prefix: 'BP.24'
          },
          {
            rombelKey: 'XII-BP-3',
            majorCode: 'BP',
            majorName: 'Broadcasting dan Perfilman',
            rombel: 3,
            maleCount: 10,
            femaleCount: 16,
            prefix: 'BP.24'
          },
          {
            rombelKey: 'XII-DKV-1',
            majorCode: 'DKV',
            majorName: 'Desain Komunikasi Visual',
            rombel: 1,
            maleCount: 17,
            femaleCount: 14,
            prefix: 'DKV.24'
          },
          {
            rombelKey: 'XII-DKV-2',
            majorCode: 'DKV',
            majorName: 'Desain Komunikasi Visual',
            rombel: 2,
            maleCount: 17,
            femaleCount: 15,
            prefix: 'DKV.24'
          },
          {
            rombelKey: 'XII-DKV-3',
            majorCode: 'DKV',
            majorName: 'Desain Komunikasi Visual',
            rombel: 3,
            maleCount: 17,
            femaleCount: 14,
            prefix: 'DKV.24'
          },
          {
            rombelKey: 'XII-TE-1',
            majorCode: 'TE',
            majorName: 'Teknik Elektronika',
            rombel: 1,
            maleCount: 34,
            femaleCount: 0,
            prefix: 'TE.24'
          },
          {
            rombelKey: 'XII-TE-2',
            majorCode: 'TE',
            majorName: 'Teknik Elektronika',
            rombel: 2,
            maleCount: 33,
            femaleCount: 1,
            prefix: 'TE.24'
          },
          {
            rombelKey: 'XII-TO-1',
            majorCode: 'TO',
            majorName: 'Teknik Otomotif',
            rombel: 1,
            maleCount: 32,
            femaleCount: 0,
            prefix: 'TO.24'
          },
          {
            rombelKey: 'XII-TO-2',
            majorCode: 'TO',
            majorName: 'Teknik Otomotif',
            rombel: 2,
            maleCount: 32,
            femaleCount: 0,
            prefix: 'TO.24'
          }
        ]

  return classConfigs.map((cfg, idx) => {
    const totalCount = cfg.maleCount + cfg.femaleCount
    const students: LeggerStudentItem[] = []
    let currentId = 1000 + idx * 40

    for (let i = 1; i <= totalCount; i++) {
      const isMale = i <= cfg.maleCount
      currentId++
      students.push({
        no: i,
        nis: `${cfg.prefix}-${currentId}`,
        name: `Siswa ${cfg.rombelKey} #${i}`,
        gender: isMale ? 'L' : 'P'
      })
    }

    return {
      classKey: cfg.rombelKey,
      className: cfg.rombelKey,
      level,
      majorCode: cfg.majorCode,
      majorName: cfg.majorName,
      rombel: cfg.rombel,
      homeroomTeacherName: `Wali Kelas ${cfg.rombelKey}`,
      maleCount: cfg.maleCount,
      femaleCount: cfg.femaleCount,
      totalCount,
      students
    }
  })
}
